#!/usr/bin/env bash

source $(dirname $0)/project/common.sh

docker exec \
    --env CONTAINER_WORKSPACE_LINK=/home/$CONTAINER_USER \
    --env TERM=xterm-256color \
    --interactive \
    --tty \
    --user $CONTAINER_USER \
    $CONTAINER_NAME \
    enter-container-shell
