#!/usr/bin/env bash

source $(dirname $0)/project/common.sh
source $(dirname $0)/project/utils.sh

HOST_USER_GID=$(id --group)
HOST_USER_UID=$(id --user)
EXTRA_ARGS=$@

list_dangling_images() {
    docker images --filter "dangling=true" --quiet || exit_on_error
}

build_image() {
    docker build \
        --build-arg CONTAINER_HOME=${CONTAINER_HOME:?} \
        --build-arg CONTAINER_PERSISTENT_DIR=${CONTAINER_PERSISTENT_DIR:?} \
        --build-arg CONTAINER_REPO_DIR=${CONTAINER_REPO_DIR:?} \
        --build-arg CONTAINER_USER=${CONTAINER_USER:?} \
        --build-arg HOST_USER_GID=${HOST_USER_GID:?} \
        --build-arg HOST_USER_UID=${HOST_USER_UID:?} \
        --build-arg TIMEZONE=$(cat /etc/timezone) \
        --tag $IMAGE_NAME \
        $EXTRA_ARGS \
        $DOCKER_DIR || exit_on_error
}

release_dangling_images() {
    echo Releasing dangling images ...
    for image in $DANGLING_IMAGES_AFTER; do
        if [ -z "$(echo $DANGLING_IMAGES_BEFORE | grep $image)" ]; then
            docker rmi $image || exit_on_error
        fi
    done
}

DANGLING_IMAGES_BEFORE=$(list_dangling_images)
build_image
DANGLING_IMAGES_AFTER=$(list_dangling_images)
release_dangling_images
