#!/usr/bin/env python

import signal
import time

class SignalCatcher:

    def __init__(self):
        self.caughtSignal = False
        signal.signal(signal.SIGTERM, self.on_signal)

    def on_signal(self, signum, frame):
        self.caughtSignal = True

if __name__ == "__main__":
    signalCatcher = SignalCatcher()
    while not signalCatcher.caughtSignal:
        time.sleep(1)
