#!/usr/bin/env bash

source utils.sh

sudo pip3 install opencv-python numpy
sudo apt-get update || exit_on_error
# OpenGL
sudo apt-get install -y libgl1-mesa-glx || exit_on_error

# Install Opencv Aruco Detection Dependencies in Python3
python3 -m pip install opencv-contrib-python || exit_on_error
