#!/usr/bin/env bash

source utils.sh

apt-get update || exit_on_error
apt-get install -y \
    build-essential \
    software-properties-common \
    wget \
    iputils-ping \
    net-tools \
    vim \
    htop \
    curl \
    || exit_on_error
