#!/usr/bin/env bash

source utils.sh

sudo add-apt-repository ppa:deadsnakes/ppa
apt-get update || exit_on_error
apt-get install -y \
    python \
    python-pip \
    python3 \
    python3-pip \
    python3.6 \
    python3.6-dev \
     || exit_on_error

sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
sudo update-alternatives --config python3

sudo pip3 install --upgrade pip==20.0.2
